apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dagster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: dagster
    repoURL: https://dagster-io.github.io/helm
    targetRevision: 1.10.2
    helm:
      valuesObject:
        dagster-user-deployments:
          deployments:
            - name: platform
              image: ghcr.io/sgc-kn/platform
              tag: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: dagster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
