apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dagster2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: dagster
    repoURL: https://dagster-io.github.io/helm
    targetRevision: 1.10.1
  destination:
    server: "https://kubernetes.default.svc"
    namespace: dagster2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
