apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dagster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: dagster
    repoURL: https://dagster-io.github.io/helm
    targetRevision: 1.10.2
    helm:
      parameters:
        - name: dagster-user-deployments.deployments[0].name
          value: platform
        - name: dagster-user-deployments.deployments[0].image
          value: ghcr.io/sgc-kn/platform
        - name: dagster-user-deployments.deployments[0].tag
          value: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: dagster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
