apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform
spec:
  template:
    spec:
      containers:
        - name: platform
          image: ghcr.io/sgc-kn/platform:v0.1.9-a5515d63
          env:
            - name: DAGSTER_CURRENT_IMAGE
              value: ghcr.io/sgc-kn/platform:v0.1.9-a5515d63
