apiVersion: v2
type: application
name: ingress-nginx

version: 4.12.0     # reuse ingress-nginx helm chart version
appVersion: 4.12.0  # reuse ingress-nginx helm chart version

dependencies:
  - name: ingress-nginx
    repository: https://kubernetes.github.io/ingress-nginx
    version: 4.12.0
