apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: infisical-platform
spec:
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: dagster

  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: infisical-platform

    # kubernetes secret name
    target:
      name: platform-env

    # load all secrets
    dataFrom:
      - find:
          name:
            regexp: .*
