apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: infisical-platform
  annotations:
    config.kubernetes.io/depends-on: /ClusterSecretStore/infisical-platform # prevent deadlock during cluster setup
spec:
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: dagster

  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: infisical-platform

    # kubernetes secret name
    target:
      name: platform-env

    # load all secrets
    dataFrom:
      - find:
          name:
            regexp: .*
