apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: infisical-platform
spec:
  provider:
    infisical:
      hostAPI: https://eu.infisical.com
      auth: # cluster side
        universalAuthCredentials:
          clientId:
            key: clientId
            name: infisical-machine-auth
            namespace: infisical-platform-credentials
          clientSecret:
            key: clientSecret
            name: infisical-machine-auth
            namespace: infisical-platform-credentials
      secretsScope: # infisical side
        projectSlug: example-project-7-tc-x
        environmentSlug: invalid-set-me-for-each-env
        secretsPath: / # Root is "/"
        recursive: true # Default is false
