apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform
spec:
  selector:
    matchLabels:
      app: platform
  replicas: 1
  template:
    metadata:
      labels:
        app: platform
    spec:
      containers:
        - name: platform
          image: ghcr.io/sgc-kn/platform:kustomize-this-label
          ports:
            - containerPort: 80
