apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: infisical
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-platform

  # kubernetes secret name
  target:
    name: platform-env

  # load all secrets
  dataFrom:
    - find:
        name:
          regexp: .*
