apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dagster-manages-jobs
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dagster-manages-jobs
subjects:
  - kind: ServiceAccount
    name: dagster
    namespace: dagster
roleRef:
  kind: Role
  name: dagster-manages-jobs
  apiGroup: rbac.authorization.k8s.io
