# The Helm chart allows configuring user deployments but we need more control.
# We deploy our platform code manually and link manually instead.
dagster:
  dagsterDaemon:
    runCoordinator:
      type: QueuedRunCoordinator
      config:
        queuedRunCoordinator:
          maxConcurrentRuns: 1
          dequeueNumWorkers: 1
  dagster-user-deployments:
    enabled: true
    enableSubchart: true
    deployments:
      - name: platform
        image:
          repository: ghcr.io/sgc-kn/platform
          tag: v0.1.56-0365eee2 # ghcr.io/sgc-kn/platform
          pullPolicy: IfNotPresent
        port: 80
        env:
          - name: ENABLE_ALL_SCHEDULES
            value: '' # value does not matter; unset variable if need be
        envSecrets:
          - name: platform-env
  runLauncher:
    type: K8sRunLauncher
    config:
      k8sRunLauncher:
        runK8sConfig:
          jobMetadata:
            annotations:
              argocd.argoproj.io/compare-options: IgnoreExtraneous
              argocd.argoproj.io/sync-options: Prune=false
