dagster:
  dagster-user-deployments:
    deployments:
      - name: platform
        image:
          repository: ghcr.io/sgc-kn/platform
          tag: v0.1.1-4035e4da # sgc-kn/platform
          pullPolicy: Always
        port: 80
