name: "traefik"

sources:
  github:
    kind: "githubrelease"
    spec:
      owner: "traefik"
      repository: "traefik-helm-chart"
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      username: '{{ requiredEnv "GITHUB_ACTOR" }}'
      versionfilter:
        kind: "regex"
        pattern: '^v.*'

conditions:
  chart-available:
    kind: "helmchart"
    spec:
      url: "https://traefik.github.io/charts"
      name: "traefik"
      version: '{{ source "github" }}'

targets:
  chart:
    kind: "file"
    spec:
      file: apps/traefik/envs/*/Chart.yaml
      searchpattern: true  # enable glob in file
      matchpattern: '(version|appVersion): .*'
      replacepattern: '$1: {{ source "github" }}'
