apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
data:
  # disable tls on internal endpoint
  server.insecure: "true"
  # set up public location of web interface
  server.basehref: "/argocd"
  server.rootpath: "/argocd"
