apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-server
spec:
  parentRefs:
  - name: gateway
    namespace: nginx-gateway
    sectionName: http
  rules:
  - matches:
    - path:
        value: /argocd
    backendRefs:
    - name: argocd-server
      port: 80
