# The Helm chart allows configuring user deployments but we need more control.
# We deploy our platform code manually and link manually instead.
dagster:
  dagster-user-deployments:
    enabled: true
    enableSubchart: true
    deployments:
      - name: platform
        image:
          repository: ghcr.io/sgc-kn/platform
          tag: v0.1.9-a5515d63 # ghcr.io/sgc-kn/platform
          pullPolicy: IfNotPresent
        port: 80
        envSecrets:
          - name: platform-env
  runLauncher:
    type: K8sRunLauncher
    config:
      k8sRunLauncher:
        runK8sConfig:
          jobMetadata:
            annotations:
              argocd.argoproj.io/compare-options: IgnoreExtraneous
