apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: infisical-platform
spec:
  provider:
    infisical:
      secretsScope:
        environmentSlug: prod
  conditions:
    - namespaces:
      - "platform-dev"
