apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: whoami
spec:
  parentRefs:
  - name: gateway
    namespace: nginx-gateway
    sectionName: http
  rules:
  - matches:
    - path:
        value: /whoami
    backendRefs:
    - name: whoami
      port: 80
