apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prod
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: git@github.com:sgc-kn/infra.git
      revision: HEAD
      directories:
      - path: apps/*/envs/prod
  template:
    metadata:
      name: '{{index .path.segments 1}}'
      labels:
        sgc-kn/appset: prod
    spec:
      project: default
      source:
        repoURL: git@github.com:sgc-kn/infra.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{index .path.segments 1}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            sgc-kn/appset: prod
            sgc-kn/manager: argocd
        syncOptions:
          - CreateNamespace=true
